title: carlospolanco.dev
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "capolanco10.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Carlos Polanco
author-img: david-freeman.jpg # add your photo
about-author: Apasionado por innovación y el mejoramiento continuo. Con 2 años de experiencia bajo el rol de Scrum Master al servicio del equipo de desarrollo con el fin de lograr los mejores resultados.
              Con más de 10 años de experiencia en desarrollo de software, enfocados en la experiencia y satisfacción de los clientes, desde la etapa de viabilidad hasta la ejecución y cierre bajo el marco de buenas prácticas.
social-twitter: capolanco10
#social-facebook:
social-github: capolanco10
social-linkedin: carlospolancodev
social-email: carlos.polanco010@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
